apiVersion: terraform.core.oam.dev/v1beta1
kind: Provider
metadata:
  name: default
spec:
  provider: gcp
  region: us-central1
  credentials:
    source: Secret
    secretRef:
      namespace: vela-system
      name: gcp-account-creds
      key: credentials
