apiVersion: terraform.core.oam.dev/v1beta1
kind: Configuration
metadata:
  name: alibaba-eip-remote
spec:
  remote: https://github.com/zzxwill/terraform-alibaba-eip.git

  variable:
    name: poc
    bandwidth: 1

  writeConnectionSecretToRef:
    name: eip-conn
    namespace: default
