version: "2"
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unconvert
    - unparam
    - zerologlint
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 3
      min-occurrences: 5
      ignore-tests: true
    gocritic:
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    gocyclo:
      min-complexity: 32
    lll:
      tab-width: 1
    makezero:
      always: false
    nakedret:
      max-func-lines: 30
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - exportloopref
          - gocyclo
          - gosec
          - unparam
        path: _test(ing)?\.go
      - linters:
          - gocritic
        path: _test\.go
        text: (unnamedResult|exitAfterDefer)
      - linters:
          - gocritic
        text: '(hugeParam|rangeValCopy):'
      - linters:
          - staticcheck
        text: 'SA3000:'
      - linters:
          - gosec
        text: 'G101:'
      - linters:
          - gosec
        text: 'G104:'
      - linters:
          - errcheck
        text: \.AddToUserAgent
      - linters:
          - revive
        text: don't use an underscore
      - linters:
          - revive
        text: 'package-comments:'
      - linters:
          - revive
        text: 'exported:'
    paths:
      - zz_generated\..+\.go$
      - .*_test.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - zz_generated\..+\.go$
      - .*_test.go$
      - third_party$
      - builtin$
      - examples$
