apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-provider-creds
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"
