---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: tf-api-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - terraform.core.oam.dev
    resources:
      - configurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - terraform.core.oam.dev
    resources:
      - configurations/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - terraform.core.oam.dev
    resources:
      - providers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - terraform.core.oam.dev
    resources:
      - providers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "delete"
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "create"
      - "update"
      - "get"
      - "delete"
