apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tf-controller-role
rules:
# All below are rules needed by pod to create ConfigMaps & Jobs
- apiGroups:
    - ""
  resources:
    - "configmaps"
  verbs:
    - "create"
    - "update"
    - "get"
    - "delete"
- apiGroups:
    - "batch"
  resources:
    - "jobs"
  verbs:
    - "create"
    - "get"
    - "list"
    - "delete"
