apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-controller-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-controller-clusterrole
subjects:
  - kind: ServiceAccount
    name: tf-controller-service-account
    namespace: {{ .Release.Namespace }}
