apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform-controller-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tf-controller-role
subjects:
- kind: ServiceAccount
  name: tf-controller-service-account
  namespace: {{ .Release.Namespace }}
