apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tf-controller-clusterrole
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
    verbs:
      - "list"
      - "watch"
  # Required to write terraform outputs
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "list"
      - "create"
      - "update"
      - "watch"
      - "delete"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
    verbs:
      - "list"
      - "watch"

  - apiGroups:
      - ""
    resources:
      - pods/log
      - pods
    verbs:
      - get
      - list
      - create
      - update
      - delete