apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tf-executor-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tf-executor-role
subjects:
  - kind: ServiceAccount
    name: tf-executor-service-account
    namespace: {{ .Release.Namespace }}
