apiVersion: terraform.core.oam.dev/v1beta1
kind: Provider
metadata:
  name: ucloud
spec:
  provider: ucloud
  region: cn-bj2
  credentials:
    source: Secret
    secretRef:
      namespace: vela-system
      name: ucloud-account-creds
      key: credentials
