# permissions for end users to view configurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configuration-viewer-role
rules:
- apiGroups:
  - terraform.core.oam.dev
  resources:
  - configurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terraform.core.oam.dev
  resources:
  - configurations/status
  verbs:
  - get
