# permissions for end users to edit providerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: providerconfig-editor-role
rules:
- apiGroups:
  - terraform.core.oam.dev
  resources:
  - providerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.core.oam.dev
  resources:
  - providerconfigs/status
  verbs:
  - get
