# permissions for end users to view providerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: providerconfig-viewer-role
rules:
- apiGroups:
  - terraform.core.oam.dev
  resources:
  - providerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - terraform.core.oam.dev
  resources:
  - providerconfigs/status
  verbs:
  - get
