
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - terraform.core.oam.dev
  resources:
  - configurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.core.oam.dev
  resources:
  - configurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - terraform.core.oam.dev
  resources:
  - providerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terraform.core.oam.dev
  resources:
  - providerconfigs/status
  verbs:
  - get
  - patch
  - update
