apiVersion: terraform.core.oam.dev/v1beta1
kind: Configuration
metadata:
  name: aws-s3
spec:
  remote: https://github.com/kubevela-contrib/terraform-modules.git
  path: aws/s3

  variable:
    bucket: "vela-website-aws-202101019"
    acl: "private"

  providerRef:
    name: aws
    namespace: default

  writeConnectionSecretToRef:
    name: s3-conn
    namespace: default
