apiVersion: terraform.core.oam.dev/v1beta1
kind: Provider
metadata:
  name: aws
spec:
  provider: aws
  region: us-east-1
  credentials:
    source: Secret
    secretRef:
      namespace: vela-system
      name: aws-account-creds
      key: credentials
