apiVersion: terraform.core.oam.dev/v1beta1
kind: Configuration
metadata:
  name: aliyun-oss
spec:
  JSON: |
    {
      "resource": {
        "alicloud_oss_bucket": {
          "bucket-acl": {
            "bucket": "${var.bucket}",
            "acl": "private"
          }
        }
      },
      "resource": {
        "alicloud_oss_bucket2": {
          "bucket-acl": {
            "bucket": "${var.bucket}",
            "acl": "private"
          }
        }
      },
      "output": {
        "BUCKET_NAME": {
          "value": "${alicloud_oss_bucket.bucket-acl.bucket}.${alicloud_oss_bucket.bucket-acl.extranet_endpoint}"
        }
      }
    }

  variable:
    bucket: "vela-website"

