#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: tfstate-retriever
#  labels:
#    account: ratings
#
#---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tf-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "secrets"
    verbs:
      - "create"
      - "update"
      - "get"
      - "list"
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "create"
      - "update"
      - "get"
      - "list"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tf-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-clusterrole
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
