apiVersion: terraform.core.oam.dev/v1beta2
kind: Configuration
metadata:
  name: aws-s3
spec:
  remote: https://github.com/kubevela-contrib/terraform-modules.git
  path: aws/s3

  variable:
    bucket: "vela-website-aws-20220628"
    acl: "private"

  backend:
    backendType: s3
    s3:
      region: us-east-1
      bucket: tf-controller-test
      key: example.state

  deleteResource: true

  providerRef:
    name: aws
    namespace: default

  writeConnectionSecretToRef:
    name: s3-conn
    namespace: default
