apiVersion: terraform.core.oam.dev/v1beta2
kind: Configuration
metadata:
  name: random-e2e-delete-provisioning-resources
spec:
  hcl: |
    resource "random_id" "server" {
      byte_length = 8
    }
    resource "random_id" "error" {
      byte_length = -1
    }

  inlineCredentials: true

  writeConnectionSecretToRef:
    name: random-conn
    namespace: default
