apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - watch
  - create
  - update
  - list
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - watch
  - list