apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: modules.terraform.core.oam.dev
spec:
  group: terraform.core.oam.dev
  version: v1
  names:
    kind: Module
    plural: modules
    singular: module
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: states.terraform.core.oam.dev
spec:
  group: terraform.core.oam.dev
  version: v1
  names:
    kind: State
    plural: states
    singular: state
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: executions.terraform.core.oam.dev
spec:
  group: terraform.core.oam.dev
  version: v1
  names:
    kind: Execution
    plural: executions
    singular: execution
  scope: Namespaced