on: push

env:
  KUBECONFIG: ~/.kube/config


jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: ${{ env.KIND_VERSION }}
          skipClusterCreation: true

      - name: Setup Kind Cluster
        run: |
          kind delete cluster
          kind create cluster --image kindest/node:v1.20.7
          kubectl version
          kubectl cluster-info

      - uses: azure/k8s-create-secret@v1
        with:
          namespace: 'default'
          secret-type: 'generic'
          arguments: --from-literal=account-name=${{ secrets.ALICLOUD_ACCESS_KEY }} --from-literal=access-key=${{ secrets.ALICLOUD_SECRET_KEY }}
          secret-name: azure-storage